# data
# data_path: "./dataset/Hissabeth.jpg"
# data_path: "./dataset/single.png" 
data_path: "./dataset/mao.jpg" 

# backend
backend_type: "pytorch"     # 量子计算后端类型，可选 "jax" 或 "pytorch"
strategy_mode: "balanced"   # Siamese 引擎的策略模式, 可选 "fast"、 "balanced"、"full"

# 模型参数
model_params:
  target_size: [1024, 1024]   # 目标图像大小 [高度, 宽度]
  BOND_DIM: 2                 # graph 中的键值（bond dimension）
  n_cores: 10                  # core 的数量
  auto_graph: True          # 是否自动配置图结构
  qctn_graph: |-            # 量子电路拓扑结构
    -2-c-2-
    -8-b-8-
    -8-a-8-
    


# 训练参数
training_params:
  method: 'adam'            # 优化方法，可选 'sgdg' 或 'adam'
  lr_rate: null             # 学习率
  lr_schedule: 
    - [0, 1e-1]
    - [1000, 1e-2]
    - [2000, 5e-3]
    - [3000, 1e-3]
    - [4000, 1e-3]
    - [6000, 1e-4]
    - [7000, 5e-5] 
    - [8000, 1e-5]            # 学习率调度表，格式为 [迭代次数, 学习率]
  max_iter: 10000             # 最大迭代次数
  tol: 1e-5                 # 收敛容忍度
  beta1: 0.9                # Adam 优化器的 beta1 参数
  beta2: 0.999              # Adam 优化器的 beta2 参数
  epsilon: 1e-8             # 防止除以零的小常数
  momentum: 0.0             # SGDG 优化器的动量参数
  stiefel: False             # 是否在 Stiefel 流形上进行优化

# 后处理参数
post_processing_params:
  plot_loss: True           # 是否绘制损失曲线图

save_params:
  output_dir: "./results/"
  save_name: "model_cores.safetensors"